name: Sync Applications Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Läuft jede Stunde
  workflow_dispatch: # Manuelles Starten möglich
  repository_dispatch:
    types: [application-update]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `groupxyz2.github.io`
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone `applications` Repository
        run: |
          git clone --depth=1 https://github.com/GroupXyz2/applications.git temp_repo

      - name: Copy index.html to `downloader`
        run: |
          rm -rf downloader
          mkdir -p downloader
          cp temp_repo/Youtube\ downloader\ website/index.html downloader/

      - name: Modify website URL to pickaxegaming.de
        run: |
          sed -i 's|example\.com|downloader.groupxyz.me|g' downloader/index.html

      #- name: Change port
      #  run: |
      #    sed -i 's|:8081|:27015|g' downloader/index.html 

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-sync index.html to downloader" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
